### ISSUE TITLE
fix position not working when integrate with ionic 2

### ISSUE THREAD

**Issue by jeremyshao830413** [leftstick/angular2-baidu-map#7]
When I integrate with ionic 2 to build baidu-map tasks, when I try fix position on web browser, it works. While after building and run in mobile phones, it failed to fix position

**Comment by leftstick** [comment]
seems css issue? Can you try with a simple `div` block instead of `baidu-map` to see if it is working?

**Comment by 1620165757** [comment]
Could not resolve 'angular2-baidu-map/dist/angular2-baidu-map/index  
why i have this matter

**Comment by leftstick** [comment]
@1620165757 is it related with the styling issue? If not, please open another issue, and provide more information of how you produced the error

**Comment by 1620165757** [comment]
I don't konw how to add the picture in there,so i sent an email to you(notifications@github.com)

**Comment by acqj** [comment]
excuse me,this map can Provide query and planning route interface?

**Comment by leftstick** [comment]
Hi @acqj , you should not ask question here, since it's nothing to do with the issue topic itself. You can open another issue for it. This is for trackable reason.

And sorry, i will not working on this project for a while due to healthy issue, so no further plan for this repo. If you have any idea, you can provide my PR
