### ISSUE TITLE
When I was in the ionic2 project

### ISSUE THREAD

**Issue by kubili2013** [leftstick/angular2-baidu-map#9]
`import {BaiduMap, OfflineOptions, ControlAnchor, NavigationControlType} from 'angular2-baidu-map';`
bundle dev failed:  Module node_modules/angular2-baidu-map/dist/angular2-baidu-map.js does not export ControlAnchor (imported by src/pages/home/home.ts)

**Comment by 1620165757** [comment]
我也遇到过这个问题，但是我重新install后，我的导包路径变了，报无法解析的错误

**Comment by leftstick** [comment]
This is weird, can u provide a playable demo i can use for reproduce this issue?

**Comment by acqj** [comment]
## `bundle update failed: 'ControlAnchor' is not exported by node_modules/angular2-baidu-map/dist/angular2-baidu-map.js
            (imported by src/pages/hospital-map/hospital-map.ts). `

I have encountered this problem ,  Please give me a solution quickly, thankyou,I'm getting very nervous.

**Comment by leftstick** [comment]
What version ur using? I am pretty sure, that `ControlAnchor` was exported correctly, see it here: [ControlAnchor](https://github.com/leftstick/angular2-baidu-map/blob/master/dist/angular2-baidu-map/index.d.ts#L28)

**Comment by acqj** [comment]
你使用的是ionic吗 我的index.d.ts里面 也一样export了ControlAnchor  但就是报这样的错

我的版本是 angular2-baidu-map@2.5.0

**Comment by leftstick** [comment]
@acqj  i don't familiar with ionic. No idea how it works, but seems `ionic` use `rollup` internally as build tool from the URL u provided。

My demo was written with `webpack` as build tool.

`export` part should not have problem, since `d.ts` were generated by `typescript`.

I think the issue is caused by the tree-shaking feature in `rollup` if you u guys are using it as build tool.

`angular2-baidu-map` is published in `commonjs` version, if you see [tsconfig](https://github.com/leftstick/angular2-baidu-map/blob/master/tsconfig.json#L5), and tree-shaking feature in `rollup` requires the module have to be written in `es6 module` standard.

I think the way to solve this issue, you can try replace your code, change:

```
import { BaiduMap, OfflineOptions, ControlAnchor, NavigationControlType} from 'angular2-baidu-map';
```

into 

```
import { BaiduMap, OfflineOptions, ControlAnchor, NavigationControlType} from 'angular2-baidu-map/src/index';
```

Build from source directly, may solve the issue.
